
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the wait-for-it script and make it executable
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Copy the project files into the container
COPY . .

# Expose port 8000 for the Django app
EXPOSE 8000

# Run the Django application with Gunicorn and ensure it waits for the database to be ready
CMD ["/wait-for-it.sh", "db:5432", "--", "gunicorn", "vaccination_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
