# Generated by Django 5.1 on 2024-08-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='vaccination.location'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_details', to='vaccination.centre'),
        ),
        migrations.AlterField(
            model_name='vaccinationslot',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_slots', to='vaccination.patient'),
        ),
    ]
