# Generated by Django 5.1 on 2024-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_alter_centre_location_alter_patient_centre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('locationState', models.CharField(max_length=255)),
                ('locationCountry', models.CharField(max_length=255)),
                ('centre', models.CharField(max_length=255)),
                ('centreAddress', models.CharField(max_length=255)),
                ('patient', models.CharField(max_length=255)),
                ('patientAge', models.CharField(max_length=10)),
                ('patientContact', models.CharField(max_length=255)),
                ('slot', models.CharField(max_length=255)),
                ('slotDate', models.DateField()),
                ('slotTime', models.TimeField()),
                ('availableSlots', models.CharField(max_length=10)),
            ],
        ),
    ]
